CREATE TABLE `Assets` (`Id` bigint(14) unsigned NOT NULL auto_increment,`AssetTag` varchar(10) NOT NULL default '0',`AssetType` tinytext,`AssetSupplier` tinytext,`AssetModel` tinytext,`AssetSerial` tinytext,`AssetPrice` double default NULL,`name` tinytext,`exp_date` TEXT,PRIMARY KEY  (`Id`),UNIQUE KEY `AssetTag` (`AssetTag`)) TYPE=MyISAM;
CREATE TABLE `Assignments` (`id` int(10) unsigned NOT NULL auto_increment,`EmployeeId` int(14) default '0',`AssetId` int(14) default '0',`StartDate` bigint(14) unsigned default '0',`EndDate` bigint(14) unsigned default '0',`Approve` tinyint(3) unsigned default '0',`Temp` tinyint(3) unsigned default '0',`Completed` int(10) unsigned default '0',PRIMARY KEY  (`id`)) TYPE=MyISAM;
CREATE TABLE `Employees` (`Id` bigint(14) unsigned NOT NULL auto_increment,`LoginName` varchar(30) default NULL,`UserPass` varchar(30) default NULL,`AccessLevel` tinyint(3) unsigned default NULL,`LastName` varchar(50) default NULL,`FirstName` varchar(50) default NULL,`EMail` varchar(150) default NULL,`Tel` tinytext,`Organization` tinytext,`Dept` tinytext,`Building` tinytext,`Floor` tinytext,`Workstation` tinytext,`Active` tinyint(3) default NULL,`Verified` bigint(14) unsigned NOT NULL default '0',`PerDiem` double NOT NULL default '0',`SessionId` varchar(50) default NULL,PRIMARY KEY  (`Id`)) TYPE=MyISAM;
CREATE TABLE `IP` (`id` int(11) NOT NULL auto_increment,`assetid` int(10) unsigned default NULL,`employeeid` int(10) unsigned default NULL,`ip` varchar(20) default '0',PRIMARY KEY  (`id`)) TYPE=MyISAM;
CREATE TABLE `LicenseOwners` (`id` int(10) unsigned NOT NULL auto_increment,`assetid` int(10) unsigned default NULL,`licenseid` varchar(100) default NULL,PRIMARY KEY  (`id`)) TYPE=MyISAM;
CREATE TABLE `Licenses` (`id` int(10) unsigned NOT NULL auto_increment,`manufacturer` varchar(100) default NULL,`product` varchar(100) default NULL,`paymentmethod` varchar(50) default NULL,`price` double default NULL,`qty` int(10) unsigned default NULL,`oem` tinyint(3) unsigned default NULL,`purchasedate` bigint(20) unsigned default NULL,`expiredate` BIGINT(20)  UNSIGNED, `licensekey` TEXT,PRIMARY KEY  (`id`)) TYPE=MyISAM;
CREATE TABLE `Links` (`id` int(10) unsigned NOT NULL auto_increment,`supplier` tinytext,`link` text,PRIMARY KEY  (`id`),KEY `id` (`id`)) TYPE=MyISAM;
CREATE TABLE `Msgs` (`id` int(10) unsigned NOT NULL auto_increment,`employeeid` int(11) default NULL,`assetid` int(11) default NULL,`date` int(14) unsigned default '0',`msgcode` tinyint(4) default NULL,`msg` text,PRIMARY KEY  (`id`)) TYPE=MyISAM;
INSERT INTO Employees (LastName,FirstName,LoginName,UserPass,AccessLevel,Active) VALUES ('Admin','Admin','Admin',Password(''),2,1)

